In [ ]:
# Name: Neha S
# Reg No: 24-27-23
# Subject: DSTT
# Programme: M.Tech (Data Science)
# Assignment Number: 2

In [24]:
#Question 1:
import numpy as np

#Q-1: a)

var1 = np.arange(31)
print("var1:", var1)
print("var1 shape:", var1.shape)

#Q-1: b)

var1 = np.arange(0, 31)
var2 = var1.reshape(31, 1)
print("\nvar2 (reshaped into 1x31):")
print(var2)
print("Shape of var2:", var2.shape)

#Q-1: c)

var3 = var1.reshape(1, 31, 1)  
print("var3 (reshaped into 3D array):")
print(var3)
print("var3 shape:", var3.shape)

#Q-1: d)

var2 = var1.reshape(31, 1)  
var2[1, 0] = -1
print("\nModified var2:")
print(var2)

#Q-1: e)

sum_var3_axis_1 = np.sum(var3, axis=1)
print("\nSum of var3 over the second dimension (axis=1):")
print(sum_var3_axis_1)

sum_var3_axis_2 = np.sum(var3, axis=2)
print("\nSum of var3 over the third dimension (axis=2):")
print(sum_var3_axis_2)

sum_var3_axis_0_2 = np.sum(var3, axis=(0, 2))
print("\nSum of var3 over the first and third dimensions (axis=0,2):")
print(sum_var3_axis_0_2)

#Q-1: f)

second_row_var2 = var2[1, :]
print("\nSecond row of var2:")
print(second_row_var2)

last_column_var2 = var2[:, -1]
print("\nLast column of var2:")
print(last_column_var2)

top_right_2x2_var2 = var2[:2, -2:]
print("\nTop-right 2x2 submatrix of var2:")
print(top_right_2x2_var2)

var1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
var1 shape: (31,)

var2 (reshaped into 1x31):
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
Shape of var2: (31, 1)
var3 (reshaped into 3D array):
[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]
  [22]
  [23]
  [24]
  [25]
  [26]
  [27]
  [28]
  [29]
  [30]]]
var3 shape: (1, 31, 1)

Modified var2:
[[ 0]
 [-1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]

Sum of var3 over the second dimension (axis=1):
[[463]]

Sum of var3 over the third dimension (axis=2):
[[ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19

In [25]:
#Question 2:
import numpy as np

#Q-2: a)
vector = np.arange(10) + 1

#Q-2: b)
matrix_A = vector[:, np.newaxis] + vector

#Q-2: c), d)
np.random.seed(42) # Set a seed for reproducibility
data = np.exp(np.random.randn(50, 5))

#Q-2: e)
column_means = np.mean(data, axis=0)
column_stds = np.std(data, axis=0)

#Q-2: f)
normalized = (data - column_means) / column_stds

normalized_mean = np.mean(normalized, axis=0)
normalized_std = np.std(normalized, axis=0)

print("Vector:")
print(vector)
print("Matrix A:")
print(matrix_A)
print("Data:")
print(data)
print("Column Means:")
print(column_means)
print("Column Standard Deviations:")
print(column_stds)
print("Normalized Data:")
print(normalized)
print("Normalized Mean:")
print(normalized_mean)
print("Normalized Standard Deviation:")
print(normalized_std)

Vector:
[ 1  2  3  4  5  6  7  8  9 10]
Matrix A:
[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]
Data:
[[ 1.64331272  0.87086849  1.91111824  4.58609939  0.79124045]
 [ 0.79125344  4.85113557  2.15423297  0.62533086  1.72040554]
 [ 0.62912979  0.62767689  1.27374614  0.14759544  0.17818769]
 [ 0.5699039   0.36318929  1.36922835  0.40332037  0.2435815 ]
 [ 4.33035173  0.79789657  1.06986043  0.24056903  0.58019982]
 [ 1.11730841  0.31632232  1.45600738  0.54846123  0.74699727]
 [ 0.54787583  6.37432488  0.98659345  0.34724978  2.27628542]
 [ 0.2949812   1.2322769   0.14090489  0.26495745  1.21757507]
 [ 2.09272403  1.18692779  0.89078847  0.74000103  0.22797439]
 [ 0.48682809  0.63088053  2.87807661  1.41004

In [26]:
#Question 3:

import numpy as np
import numpy.linalg as la

#Q-3: a)

def vandermonde(N):
    vec = np.arange(N) + 1  
    vander_matrix = vec[:, np.newaxis] ** np.arange(N)
    return vander_matrix

vander = vandermonde(12)
print("Vandermonde matrix for N = 12:\n", vander)

#Q-3: b)

# Create a vector of ones with length 12
x = np.ones(12)

# Perform matrix-vector multiplication
b = np.dot(vander, x)
print("\nVector b after matrix-vector multiplication:\n", b)

#Q-3: c)

# Compute the inverse of the Vandermonde matrix
vander_inv = np.linalg.inv(vander)

v = np.linalg.inv(vander)

# Multiply the inverse matrix by vector b to solve for x
x_naive = np.dot(vander_inv, b)
print("\nNaïve solution (using inverse of Vandermonde matrix):\n", x_naive)

#Q-3: d)

# Solve the system using numpy.linalg.solve
x_solve = np.linalg.solve(vander, b)
print("\nSolution using numpy.linalg.solve:\n", x_solve)

Vandermonde matrix for N = 12:
 [[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
